// Paraphrased from julyarchive.cridobd.org's day-by-day account (Section 2A of the build
// plan). Content only — never used as a registrant/name data source (that stays scraper-only,
// see Section 5).
export type TimelineDay = {
  day: number;
  bnDigits: string;
  weekdayBn: string;
  weekdayEn: string;
  gregorian: string;
  bn: string;
  en: string;
};

const BN_DIGITS = "০১২৩৪৫৬৭৮৯";
function toBnNumber(n: number): string {
  return String(n)
    .split("")
    .map((d) => BN_DIGITS[Number(d)])
    .join("");
}

const RAW: Omit<TimelineDay, "bnDigits">[] = [
  { day: 1, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "1 July", bn: "শিক্ষার্থীরা কোটা ব্যবস্থার বিরুদ্ধে তিন দিনের কর্মসূচি ঘোষণা করে এবং ২০১৮ সালের মেধাভিত্তিক নিয়োগ পরিপত্র পুনর্বহালের দাবি জানায়।", en: "Students announced a three-day program against the quota system, demanding restoration of the 2018 merit-based recruitment circular." },
  { day: 2, weekdayBn: "মঙ্গলবার", weekdayEn: "Tuesday", gregorian: "2 July", bn: "ঢাকা বিশ্ববিদ্যালয়ের কেন্দ্রীয় গ্রন্থাগার থেকে শাহবাগ পর্যন্ত মিছিল ও এক ঘণ্টার অবরোধ হয়; আরও ছয়টি বিশ্ববিদ্যালয়ে একই ধরনের কর্মসূচি পালিত হয়।", en: "A procession from Dhaka University's central library to Shahbagh blocked traffic for an hour; similar protests spread to six more universities." },
  { day: 3, weekdayBn: "বুধবার", weekdayEn: "Wednesday", gregorian: "3 July", bn: "শাহবাগসহ সাতটি বিশ্ববিদ্যালয়ে অবরোধ অব্যাহত থাকে; ময়মনসিংহে বাউয়েটের শিক্ষার্থীরা ট্রেন থামিয়ে দেন।", en: "Blockades continued at Shahbagh and six other campuses; in Mymensingh, BAUET students stopped a train." },
  { day: 4, weekdayBn: "বৃহস্পতিবার", weekdayEn: "Thursday", gregorian: "4 July", bn: "আপিল বিভাগ কোটা সংক্রান্ত রায় পিছিয়ে দেয়; শিক্ষার্থীরা শাহবাগে অনির্দিষ্টকালের অবস্থান শুরু করেন, এদিকে ছাত্রলীগ কর্মীরা হলের প্রবেশপথ আটকে দেন।", en: "The Appellate Division postponed its quota ruling; students began an indefinite sit-in at Shahbagh, while Chhatra League activists blocked hall entrances." },
  { day: 5, weekdayBn: "শুক্রবার", weekdayEn: "Friday", gregorian: "5 July", bn: "সাপ্তাহিক ছুটির দিনেও একাধিক শহরে অবরোধ ও বিক্ষোভ অব্যাহত থাকে।", en: "Despite the Friday holiday, blockades and protests continued in several cities." },
  { day: 6, weekdayBn: "শনিবার", weekdayEn: "Saturday", gregorian: "6 July", bn: "বিশ্ববিদ্যালয় ও কলেজগুলো ক্লাস-পরীক্ষা বর্জনের ঘোষণা দেয়; পরদিন সারাদেশে \"বাংলা ব্লকেড\" কর্মসূচির ডাক দেওয়া হয়।", en: "Universities and colleges announced a boycott of classes and exams; a nationwide \"Bangla Blockade\" was called for the next day." },
  { day: 7, weekdayBn: "রোববার", weekdayEn: "Sunday", gregorian: "7 July", bn: "প্রথম \"বাংলা ব্লকেড\" কর্মসূচিতে সারাদেশে প্রধান সড়ক অবরুদ্ধ হয়; রাজধানীর যান চলাচল প্রায় পাঁচ ঘণ্টা বন্ধ থাকে।", en: "The first \"Bangla Blockade\" shut down major roads nationwide; traffic in the capital stopped for about five hours." },
  { day: 8, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "8 July", bn: "৬৫ সদস্যের সমন্বয়ক কমিটি গঠিত হয়; দ্বিতীয় দফার ব্লকেডে ঢাকায় ১১টি পয়েন্টে এবং ৯টি বিশ্ববিদ্যালয়ে কর্মসূচি পালিত হয়।", en: "A 65-member coordination committee was formed; a second blockade covered 11 points in Dhaka and protests at 9 universities." },
  { day: 9, weekdayBn: "মঙ্গলবার", weekdayEn: "Tuesday", gregorian: "9 July", bn: "পরদিন হাইকোর্টের শুনানি সামনে রেখে শিক্ষার্থীদের কর্মসূচি অব্যাহত থাকে; এদিনের অবরোধ চার ঘণ্টায় সীমিত রাখা হয়।", en: "The student strike continued ahead of a High Court hearing the next day; that day's blockade ran for a shorter four hours." },
  { day: 10, weekdayBn: "বুধবার", weekdayEn: "Wednesday", gregorian: "10 July", bn: "চতুর্থ দফা অবরোধ; আপিল বিভাগ কোটা রায়ে চার সপ্তাহের স্থিতাবস্থা বহাল রাখে এবং ৭ আগস্ট পরবর্তী শুনানির দিন ধার্য করে।", en: "A fourth blockade day; the Appellate Division ordered a four-week status quo on the quota ruling, setting the next hearing for 7 August." },
  { day: 11, weekdayBn: "বৃহস্পতিবার", weekdayEn: "Thursday", gregorian: "11 July", bn: "একাধিক স্থানে পুলিশ বিক্ষোভকারীদের ওপর ব্যবস্থা নেয়; কুমিল্লার সহিংসতায় অ্যামনেস্টি ইন্টারন্যাশনাল উদ্বেগ প্রকাশ করে, যেখানে ৩০ জনের বেশি আহত হওয়ার খবর আসে।", en: "Police moved against protesters in several locations; Amnesty International raised concern over violence in Cumilla, where more than 30 people were reported injured." },
  { day: 12, weekdayBn: "শুক্রবার", weekdayEn: "Friday", gregorian: "12 July", bn: "সাপ্তাহিক ছুটিতেও অবরোধ অব্যাহত থাকে; কুমিল্লায় পুলিশ-শিক্ষার্থী সংঘর্ষ হয়, পরদিনের জন্য সমাবেশের ডাক দেওয়া হয়।", en: "The blockade continued through the Friday holiday; clashes between police and students were reported in Cumilla, with a rally planned for the next day." },
  { day: 13, weekdayBn: "শনিবার", weekdayEn: "Saturday", gregorian: "13 July", bn: "সরাসরি নিয়োগে কোটা বাতিলের পরিপত্র পুনর্বহালের দাবিতে রাষ্ট্রপতির কাছে স্মারকলিপি দেওয়ার ঘোষণা আসে; অবরোধ চলতে থাকে।", en: "Organizers announced a memorandum to the President demanding reinstatement of the circular abolishing quotas in direct recruitment; the blockade continued." },
  { day: 14, weekdayBn: "রোববার", weekdayEn: "Sunday", gregorian: "14 July", bn: "শিক্ষার্থীরা রাষ্ট্রপতির কাছে স্মারকলিপি জমা দেন এবং সরকারকে ২৪ ঘণ্টার আল্টিমেটাম দেন; প্রধানমন্ত্রী প্রকাশ্যে আন্দোলনের যৌক্তিকতা নিয়ে প্রশ্ন তোলেন।", en: "Students submitted the memorandum to the President and gave the government a 24-hour ultimatum; the Prime Minister publicly questioned the movement's reasoning." },
  { day: 15, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "15 July", bn: "একাধিক ক্যাম্পাসে ছাত্রলীগের হামলার শিকার হন আন্দোলনকারীরা; ঢাকা মেডিকেল কলেজ হাসপাতালে অন্তত ২৯৭ জন আহতের চিকিৎসা হয়।", en: "Chhatra League activists attacked protesters on multiple campuses; at least 297 injured people were treated at Dhaka Medical College Hospital." },
  { day: 16, weekdayBn: "মঙ্গলবার", weekdayEn: "Tuesday", gregorian: "16 July", bn: "সারাদেশে অন্তত ছয়জন নিহত হন — এর মধ্যে রংপুরে পুলিশের গুলিতে নিহত হন আবু সাঈদ; চট্টগ্রামে তিনজন এবং ঢাকায় দুইজনের মৃত্যু হয়।", en: "At least six protesters were killed nationwide — among them Abu Sayed, shot by police in Rangpur, with three deaths in Chattogram and two in Dhaka." },
  { day: 17, weekdayBn: "বুধবার", weekdayEn: "Wednesday", gregorian: "17 July", bn: "ছাত্রলীগকে ক্যাম্পাস থেকে নিষিদ্ধ ঘোষণা করা হয়; প্রতীকী কফিন মিছিল হয়; পুলিশ টিয়ারশেল ব্যবহার করে; সব শিক্ষাপ্রতিষ্ঠান অনির্দিষ্টকালের জন্য বন্ধ ঘোষণা করা হয়।", en: "Chhatra League was barred from campuses; coffin processions were held; police used tear gas; all educational institutions were shut indefinitely." },
  { day: 18, weekdayBn: "বৃহস্পতিবার", weekdayEn: "Thursday", gregorian: "18 July", bn: "প্রায় সর্বাত্মক শাটডাউন শুরু হয়; দেশের ৪৭টি জেলায় একদিনেই ৪১ জনের বেশি নিহত হন; বিটিভি ভবনে আগুন লাগে; মেট্রোরেল বন্ধ হয়ে যায়।", en: "A near-total shutdown began; more than 41 people were killed in a single day across 47 districts; the BTV headquarters caught fire; the metro rail was closed." },
  { day: 19, weekdayBn: "শুক্রবার", weekdayEn: "Friday", gregorian: "19 July", bn: "মৃতের সংখ্যা ৭৫ ছাড়িয়ে যায়; সারাদেশে অবকাঠামোর ক্ষতি হয়; মধ্যরাত থেকে কারফিউ জারি হয় এবং ইন্টারনেট বন্ধ করে দেওয়া হয়।", en: "The death toll passed 75; infrastructure was damaged nationwide; a curfew was declared from midnight and the internet was shut down." },
  { day: 20, weekdayBn: "শনিবার", weekdayEn: "Saturday", gregorian: "20 July", bn: "কারফিউয়ের প্রথম দিনে আরও ২৬ জন নিহত হন; সমন্বয়ক আসিফ, বাকের ও রিফাতকে কর্তৃপক্ষ কর্তৃক তুলে নেওয়ার খবর আসে।", en: "The first day of curfew saw 26 more deaths; three protest coordinators — Asif, Bakar and Riffat — were reported abducted by the authorities." },
  { day: 21, weekdayBn: "রোববার", weekdayEn: "Sunday", gregorian: "21 July", bn: "আপিল বিভাগ মেধাভিত্তিক নিয়োগ আদেশ বাতিল করে কোটা পুনর্বহাল করে — ৯৩% মেধা, ৫% মুক্তিযোদ্ধা সন্তান, ১% ক্ষুদ্র নৃগোষ্ঠী ও ১% প্রতিবন্ধী কোটা রেখে।", en: "The Appellate Division scrapped the merit-based recruitment order, restoring quotas at 93% merit, 5% freedom-fighter descendants, 1% ethnic minorities and 1% persons with disabilities." },
  { day: 22, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "22 July", bn: "সমন্বয়ক নাহিদ ইসলামকে তুলে নেওয়ার বিষয়টি নিশ্চিত হয়; ইন্টারনেট চালু, হল খুলে দেওয়া, নিরাপত্তা নিশ্চিতকরণ ও কারফিউ প্রত্যাহারের দাবিতে সমন্বয়করা ৪৮ ঘণ্টার আল্টিমেটাম দেন।", en: "The abduction of coordinator Nahid Islam was confirmed; coordinators issued a 48-hour ultimatum over internet access, hall reopening, safety guarantees, and lifting the curfew." },
  { day: 23, weekdayBn: "মঙ্গলবার", weekdayEn: "Tuesday", gregorian: "23 July", bn: "কোটা সংস্কার সংক্রান্ত প্রজ্ঞাপন জারি হয়; সীমিত পরিসরে ব্রডব্যান্ড ইন্টারনেট চালু হয়; শাহবাগে অবরোধ অব্যাহত থাকে।", en: "A quota-reform proclamation was issued; limited broadband internet was restored; the blockade at Shahbagh continued." },
  { day: 24, weekdayBn: "বুধবার", weekdayEn: "Wednesday", gregorian: "24 July", bn: "পাঁচ দিন আটক থাকার পর আসিফ ও বাকেরকে চোখ বাঁধা অবস্থায় ফেলে যাওয়া হয়; ইন্টারনেট ও গণমাধ্যমের ওপর নিষেধাজ্ঞা কিছুটা শিথিল হয়।", en: "Asif and Bakar were found blindfolded after five days in custody; internet and media restrictions were partly eased." },
  { day: 25, weekdayBn: "বৃহস্পতিবার", weekdayEn: "Thursday", gregorian: "25 July", bn: "প্রধানমন্ত্রী একটি মেট্রো স্টেশন পরিদর্শন করেন এবং আলোচনার প্রস্তাব দেন; সমন্বয়করা বলেন, আইনি ভিত্তি ছাড়া শুধু আদালতের রায় যথেষ্ট নয়।", en: "The Prime Minister visited a metro station and proposed talks; coordinators said a court ruling alone was not enough without legislation." },
  { day: 26, weekdayBn: "শুক্রবার", weekdayEn: "Friday", gregorian: "26 July", bn: "হাসপাতাল থেকে তিনজন সমন্বয়ককে পুনরায় গ্রেপ্তার করা হয়; \"ব্লক রেইড\" অভিযানের খবর আসে — সারাদেশে ৫৫৫টি মামলা ও ৬,২৬৪ জন গ্রেপ্তারের তথ্য জানা যায়।", en: "Three coordinators were re-arrested from hospital; \"block raid\" operations were reported, with 555 cases filed and 6,264 arrests nationwide." },
  { day: 27, weekdayBn: "শনিবার", weekdayEn: "Saturday", gregorian: "27 July", bn: "আরও দুইজন সমন্বয়ককে গ্রেপ্তার করা হয়; ভিডিও কলের মাধ্যমে ২৪ ঘণ্টার আল্টিমেটাম দেওয়া হয়; ইন্টারনেট বন্ধ থাকে।", en: "Two more coordinators were arrested; a 24-hour ultimatum was issued via video call; the internet blackout continued." },
  { day: 28, weekdayBn: "রোববার", weekdayEn: "Sunday", gregorian: "28 July", bn: "ছয়জন সমন্বয়ককে মুক্তি দেওয়া হয় এবং তাঁদের একটি ভিডিও বার্তায় আন্দোলন প্রত্যাহারের কথা বলা হয় — পরে যা চাপের মুখে দেওয়া বিবৃতি বলে বিতর্কিত হয়।", en: "Six coordinators were released and appeared in a video statement said to withdraw the movement — a claim later disputed as made under duress." },
  { day: 29, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "29 July", bn: "জামায়াতে ইসলামী ও তার ছাত্রসংগঠন শিবিরকে নিষিদ্ধ ঘোষণা করা হয়; হাইকোর্ট পরিস্থিতি সামলানোর ধরন নিয়ে সমালোচনা করে; সমন্বয়করা আগের প্রত্যাহার বিবৃতি প্রত্যাখ্যান করেন।", en: "Jamaat-e-Islami and its student wing Shibir were banned; the High Court criticized the authorities' handling of events; coordinators rejected the earlier withdrawal claim." },
  { day: 30, weekdayBn: "মঙ্গলবার", weekdayEn: "Tuesday", gregorian: "30 July", bn: "\"মার্চ ফর জাস্টিস\" কর্মসূচির ডাক দেওয়া হয়; সামাজিক যোগাযোগমাধ্যমে লাল প্রোফাইল ছবির প্রচলন হয়; সরকার রাষ্ট্রীয় শোক ঘোষণা প্রত্যাখ্যান করে; ফেসবুক টানা ১৩ দিন বন্ধ থাকে।", en: "A \"March for Justice\" was announced; social media filled with red profile pictures; the government declined a state mourning; Facebook remained blocked for a 13th day." },
  { day: 31, weekdayBn: "বুধবার", weekdayEn: "Wednesday", gregorian: "31 July", bn: "আদালত অবরোধ কর্মসূচি পালিত হয়; \"মার্চ ফর জাস্টিস\" পালিত হতে থাকে; ফেসবুক ও হোয়াটসঅ্যাপ পুনরায় চালু হয়।", en: "Protesters blockaded courts; \"March for Justice\" observances continued; Facebook and WhatsApp access was restored." },
  { day: 32, weekdayBn: "বৃহস্পতিবার", weekdayEn: "Thursday", gregorian: "1 August", bn: "জুলাই মাস পেরিয়ে আন্দোলন অব্যাহত থাকায় অনলাইনে প্রতীকী \"৩২ জুলাই\" বলার প্রচলন ছড়িয়ে পড়ে; সমন্বয়করা হেফাজত থেকে মুক্তি পান এবং \"স্মরণে আমাদের বীরেরা\" কর্মসূচি ঘোষিত হয়।", en: "As the movement outlasted the calendar month, the symbolic \"32 July\" framing spread online; coordinators were released from custody and a \"Remembering Our Heroes\" program was announced." },
  { day: 33, weekdayBn: "শুক্রবার", weekdayEn: "Friday", gregorian: "2 August", bn: "জুমার নামাজের পর প্রেস ক্লাব থেকে শাহবাগ পর্যন্ত মিছিলে সাধারণ মানুষ যোগ দেন; বিভিন্ন জেলায় সহিংসতা অব্যাহত থাকে।", en: "After Friday prayers, a procession from the press club to Shahbagh drew large public participation; violence continued in several districts." },
  { day: 34, weekdayBn: "শনিবার", weekdayEn: "Saturday", gregorian: "3 August", bn: "শাহবাগে বিশাল জনসমাবেশ থেকে প্রধানমন্ত্রীর পদত্যাগ দাবি করা হয়; জরুরি সেবা বাদ রেখে অসহযোগ আন্দোলনের ঘোষণা আসে।", en: "A mass gathering at Shahbagh demanded the Prime Minister's resignation; a non-cooperation movement was declared, with essential services exempted." },
  { day: 35, weekdayBn: "রোববার", weekdayEn: "Sunday", gregorian: "4 August", bn: "পূর্ণাঙ্গ অসহযোগ আন্দোলন শুরু হয়; সারাদেশে সহিংসতা ছড়িয়ে পড়ে ও সরকারি স্থাপনায় হামলা হয়; \"ঢাকার দিকে মার্চ\" কর্মসূচির ডাক দেওয়া হয়।", en: "The full non-cooperation movement began; violence spread nationwide and government offices were attacked; organizers called for a \"March to Dhaka.\"" },
  { day: 36, weekdayBn: "সোমবার", weekdayEn: "Monday", gregorian: "5 August", bn: "বিপুল জনতা ঢাকায় প্রবেশ করে; প্রধানমন্ত্রী সামরিক হেলিকপ্টারে দেশ ত্যাগ করেন এবং সরকারের পতন ঘটে।", en: "Large crowds entered Dhaka; the Prime Minister left the country by military helicopter, and the government fell." },
];

export const julyTimeline: TimelineDay[] = RAW.map((d) => ({
  ...d,
  bnDigits: toBnNumber(d.day),
}));
